#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated
git submodule init
git submodule update

# This is an app bundle being built, relocatable.
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/
./mkdist mcstas-app $1 support/MacOSX/McCode.app/ "" mac "" -- OSXapp

# For the actual mcstas part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/
# 64-bit Mac OS
./mkdist mcstas $1 "" "" mac "" -- OSXapp
./mkdist mcstas-comps $1 "" "" mac "" -- OSXapp
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac "" -- OSXapp
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-svg $1 tools/Python/mcplot/svg/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcresplot $1 tools/Python/mcresplot/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-mantid $1 tools/Python/mcdisplay/mantid_xml/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdoc $1 tools/Python/mcdoc/ "" mac "" -- OSXapp
./mkdist mcstas-clusterscripts $1 tools/cluster-scripts/ "" mac "" -- OSXapp
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" mac "" -- OSXapp

WORK=`pwd`

# NCrystal installation:
rm -rf 3rdparty-build/ncrystal/build
mkdir 3rdparty-build/ncrystal/build
cd 3rdparty-build/ncrystal/build
cmake .. -DCMAKE_INSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/ncrystal/ -DBUILD_G4HOOKS=OFF
make
make install
cd $WORK
rm -rf 3rdparty-build/ncrystal/build

echo "*********************************************************"
echo "* Embedding Python modules in your app                  *"
echo "*********************************************************"

mkdir -p $MCINSTALL_PREFIX/mcstas/$1/python/
cd $MCINSTALL_PREFIX/mcstas/$1/
ln -sf python miniconda3
mkdir -p python/lib
mkdir -p python/lib/python
mkdir -p python/lib/python/site-packages
mkdir -p python/bin
ln -sf /usr/bin/python3 python/bin/
ln -sf /usr/bin/python3 python/bin/python
ln -sf /usr/bin/python3 python/bin/pythonw
cd -

export PYVER=`/usr/bin/python3 --version | cut -f 2 -d\  | cut -f 1-2 -d.`
/usr/bin/python3 -m pip install --target=$MCINSTALL_PREFIX/mcstas/$1/python/lib/python$PYVER/site-packages --ignore-installed PyQt5 Qscintilla pyqtgraph pyaml ply numpy scipy pillow tornado jinja2 mpld3 gsl matplotlib
# Copy in the mpicc snippets
cp support/MacOSX/mpicc-wrappers/* $MCINSTALL_PREFIX/mcstas/$1/bin

echo "*********************************************************"
echo "* Building and embedding openmpi in your app            *"
echo "*********************************************************"

rm -rf openmpi-4.0.4
curl -O https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.4.tar.gz
tar xzf openmpi-4.0.4.tar.gz
cd openmpi-4.0.4
./configure --prefix=$MCINSTALL_PREFIX/mcstas/$1/ --disable-mpi-fortran
make
make install
cd -

export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/

cd $WORK
# Generate mcdoc pages
/usr/bin/python3 $MCINSTALL_PREFIX/mcstas/$1/tools/Python/mcdoc/mcdoc.py -i

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McStas-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McStas-$1.app/Contents/Resources/mcstas/$1/environment McStas-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    mv dist mcstas-$1
    mkdir dist
    tar cfz dist/mcstas-$1.tgz mcstas-$1
    cp INSTALL-McStas/macOS/README.md dist
    echo A tgz of your app is now located in the dist folder
    rm -rf mcstas-$1
else
    ln -s /Applications/McStas-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



